import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { ThemeProvider } from "@mui/material";
import { theme } from "@/theme/useTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Jewelry Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Lora:wght@400;700&family=Roboto:wght@400;700&family=Open+Sans:wght@400;700&family=Martel:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className={inter.className}>
        <ThemeProvider theme={theme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
